(ns calculator.core
  (:gen-class)
  (:import (javax.swing JPanel)
           (javax.swing JButton)
           (javax.swing JTextField)
           (java.awt BorderLayout)
           (java.awt GridLayout)
           (javax.swing JFrame)
           (java.awt.event ActionListener)))

;              (.setText textField (clojure.string/join "" [(.getText textField)(.getText (.getSource event))])))))
(defn -main
  "Main method of the project"
  []
  (def textField(JTextField. 10))
  (def total 0.0)
  (.setText textField (str total))
  (def act(proxy [ActionListener] []
            (actionPerformed [event]
              (let [s (.getText (.getSource event))]
                (cond
                  (= s "+") (do (println (var-get (def total (+ total (Double/parseDouble (.getText textField)))))) (println total) (.setText textField "0.0"))
                  (= s "-") (do (println (var-get (def total (- total (Double/parseDouble (.getText textField)))))) (println total) (.setText textField "0.0"))
                  (= s "/") (do (println (var-get (def total (/ total (Double/parseDouble (.getText textField)))))) (println total) (.setText textField "0.0"))
                  (= s "*") (do (println (var-get (def total (* total (Double/parseDouble (.getText textField)))))) (println total) (.setText textField "0.0"))
                  (= s "=") (.setText textField (str total))
                  :else (.setText textField (if (not= (.getText textField) "0.0") (clojure.string/join "" [(.getText textField) s]) s)))))))
  (def frame(JFrame. ))
  (.setSize frame 400 400)
  (.setVisible frame true)
  (.setTitle frame "Clojure Calculator")
  (def containerPanel(JPanel. (BorderLayout.)))
  (def buttonPanel(JPanel. (GridLayout. 4 4)))
  (.setContentPane frame containerPanel)
  (.add containerPanel buttonPanel BorderLayout/CENTER)
  (.add containerPanel textField BorderLayout/NORTH)
  (def one(JButton. "1"))
  (.addActionListener one act)
  (def two(JButton. "2"))
  (.addActionListener two act)
  (def three(JButton. "3"))
  (.addActionListener three act)
  (def four(JButton. "4"))
  (.addActionListener four act)
  (def five(JButton. "5"))
  (.addActionListener five act)
  (def six(JButton. "6"))
  (.addActionListener six act)
  (def seven(JButton. "7"))
  (.addActionListener seven act)
  (def eight(JButton. "8"))
  (.addActionListener eight act)
  (def nine(JButton. "9"))
  (.addActionListener nine act)
  (def zero(JButton. "0"))
  (.addActionListener zero act)
  (def plus(JButton. "+"))
  (.addActionListener plus act)
  (def minus(JButton. "-"))
  (.addActionListener minus act)
  (def divide(JButton. "/"))
  (.addActionListener divide act)
  (def times(JButton. "*"))
  (.addActionListener times act)
  (def equals(JButton. "="))
  (.addActionListener equals act)
  (def dot(JButton. "."))
  (.addActionListener dot act)
  (.add buttonPanel one)
  (.revalidate one)
  (.add buttonPanel two)
  (.revalidate two)
  (.add buttonPanel three)
  (.revalidate three)
  (.add buttonPanel plus)
  (.revalidate plus)
  (.add buttonPanel four)
  (.revalidate four)
  (.add buttonPanel five)
  (.revalidate five)
  (.add buttonPanel six)
  (.revalidate six)
  (.add buttonPanel minus)
  (.revalidate minus)
  (.add buttonPanel seven)
  (.revalidate seven)
  (.add buttonPanel eight)
  (.revalidate eight)
  (.add buttonPanel nine)
  (.revalidate nine)
  (.add buttonPanel times)
  (.revalidate times)
  (.add buttonPanel zero)
  (.revalidate zero)
  (.add buttonPanel dot)
  (.revalidate dot)
  (.add buttonPanel equals)
  (.revalidate equals)
  (.add buttonPanel divide)
  (.revalidate divide))
